#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/squareface/IdeaProjects/sell-logger/sell.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.6.81.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

